In [70]:
import pandas as pd
import numpy as np
import json
import requests as re
import boto3
from io import StringIO

In [70]:
def write_dataframe_to_s3(dataframe, bucket_name, file_name):
    """
    Write Pandas DataFrame to an S3 bucket as a CSV file.

    Parameters:
        dataframe (pandas.DataFrame): The DataFrame to be written.
        bucket_name (str): The name of the S3 bucket.
        file_name (str): The name of the CSV file to be written.

    Returns:
        None
    """
    s3 = boto3.client('s3')
    csv_buffer = StringIO()
    dataframe.to_csv(csv_buffer, index=False)

    s3.put_object(Bucket=bucket_name, Key=file_name, Body=csv_buffer.getvalue())

In [64]:
response = re.get("https://www.rotowire.com/betting/nba/tables/games-archive.php")

data = pd.DataFrame(response.json())
data = data.drop(["season", "game_time", "home_team_id", "home_team_stats_id", "visit_team_id", "visit_team_stats_id", "tipoff", "month", "start", "name", "spread"], axis = 1)

write_dataframe_to_s3(data, "bttj-final-s3", "betting_data.csv")

In [66]:
data.to_csv("BettingData.csv")

In [65]:
data.head()

,game_date,home_team_abbrev,visit_team_abbrev,home_team_score,visit_team_score,game_over_under,line,favorite,score,total,over_hit,under_hit,favorite_covered,underdog_covered
0,2017-10-17 00:00:00,CLE,BOS,102,99,216.0,-4.5,CLE,99-102,201,0,1,0,1
1,2017-10-17 00:00:00,GSW,HOU,121,122,231.0,-9.5,GSW,122-121,243,1,0,0,1
2,2017-10-18 00:00:00,DET,CHA,102,90,202.0,-2.5,DET,90-102,192,0,1,1,0
3,2017-10-18 00:00:00,IND,BKN,140,131,216.5,-3.0,IND,131-140,271,1,0,1,0
4,2017-10-18 00:00:00,ORL,MIA,116,109,205.5,3.5,MIA,109-116,225,1,0,0,1

In [59]:
data[((data["home_team_abbrev"] == "SAC") & (data["home_team_score"] > data["visit_team_score"])) | ((data["visit_team_abbrev"] == "SAC") & (data["home_team_score"] < data["visit_team_score"]))]

,game_date,home_team_abbrev,visit_team_abbrev,home_team_score,visit_team_score,game_over_under,line,favorite,score,total,over_hit,under_hit,favorite_covered,underdog_covered
23,2017-10-20 00:00:00,DAL,SAC,88,93,202.0,-6.0,DAL,93-88,181,0,1,0,1
157,2017-11-07 00:00:00,SAC,OKC,94,86,202.5,10.5,OKC,86-94,180,0,1,0,1
166,2017-11-09 00:00:00,SAC,PHI,109,108,208.0,6.5,PHI,108-109,217,1,0,0,1
224,2017-11-17 00:00:00,SAC,POR,86,82,199.0,7.0,POR,82-86,168,0,1,0,1
265,2017-11-22 00:00:00,SAC,LAL,113,102,205.5,-1.0,SAC,102-113,215,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8266,2024-02-09 00:00:00,SAC,DEN,135,106,230.0,-3.0,SAC,106-135,241,1,0,1,0
8306,2024-02-14 00:00:00,DEN,SAC,98,102,229.5,-5.5,DEN,102-98,200,0,1,0,1
8324,2024-02-22 00:00:00,SAC,SAS,127,122,242.5,-10.5,SAC,122-127,249,1,0,0,1
8348,2024-02-25 00:00:00,LAC,SAC,107,123,239.5,-4.0,LAC,123-107,230,0,1,0,1
8383,2024-03-01 00:00:00,MIN,SAC,120,124,222.5,-8.0,MIN,124-120,244,1,0,0,1

In [60]:
data[(data["home_team_abbrev"] == "SAC") | (data["visit_team_abbrev"] == "SAC")]

,game_date,home_team_abbrev,visit_team_abbrev,home_team_score,visit_team_score,game_over_under,line,favorite,score,total,over_hit,under_hit,favorite_covered,underdog_covered
12,2017-10-18 00:00:00,SAC,HOU,100,105,216.5,7.0,HOU,105-100,205,0,1,0,1
23,2017-10-20 00:00:00,DAL,SAC,88,93,202.0,-6.0,DAL,93-88,181,0,1,0,1
34,2017-10-21 00:00:00,DEN,SAC,96,79,212.5,-12.5,DEN,79-96,175,0,1,1,0
47,2017-10-23 00:00:00,PHX,SAC,117,115,206.5,2.5,SAC,115-117,232,1,0,0,1
68,2017-10-26 00:00:00,SAC,NOP,106,114,204.0,-1.0,SAC,114-106,220,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8324,2024-02-22 00:00:00,SAC,SAS,127,122,242.5,-10.5,SAC,122-127,249,1,0,0,1
8348,2024-02-25 00:00:00,LAC,SAC,107,123,239.5,-4.0,LAC,123-107,230,0,1,0,1
8352,2024-02-26 00:00:00,SAC,MIA,110,121,223.5,-7.5,SAC,121-110,231,1,0,0,1
8368,2024-02-28 00:00:00,DEN,SAC,117,96,226.5,-9.0,DEN,96-117,213,0,1,1,0
8383,2024-03-01 00:00:00,MIN,SAC,120,124,222.5,-8.0,MIN,124-120,244,1,0,0,1